import "./globals.css";
import SmoothScroll from "@/components/shared/SmoothScroll";
import GlobalBackground from "@/components/background/GlobalBackground";
import { newYork, satoshi } from "./fonts";
import SiteShell from "@/components/layout/SiteShell";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${newYork.variable} ${satoshi.variable}`}
    >
      <body className="min-h-full flex flex-col">
        <GlobalBackground />
        <SmoothScroll />

        {children}
      </body>
    </html>

    // <html
    //   lang="en"
    //   className={`${newYork.variable} ${satoshi.variable}`}
    // >
    //   <body className="min-h-full flex flex-col">
    //     <GlobalBackground />

    //     <SmoothScroll />

    //     <SiteShell />

    //     {children}
    //   </body>
    // </html>
  );
}
